# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    # Checkout repo
    - name: Check out repository
    - uses: actions/checkout@v3
    # Check out Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # Install poetry package manager
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    # Install dependencies with poetry
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
    # Run tests
    - name: Run unittests
      run: |
        source .venv/bin/activate
        python -m unittest
    # Run static checker
    - name: Run mypy
      run: |
        source .venv/bin/activate
        python -m mypy pseudocode
